name: ejazapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+31

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  audio_service: ^0.18.11
  audio_session: ^0.2.1
  badges: ^3.1.1
  bottom_navy_bar: ^6.0.0-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  cloud_firestore: ^5.6.6
  collection: ^1.18.0
  colorful_safe_area: ^1.0.0
  comment_box: ^0.0.18
  comment_tree: ^0.3.0
  confetti: ^0.8.0
  connectivity_plus: ^6.1.4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  dropdown_button2: ^2.1.4
  easy_container: ^1.0.4+1
 # external_path: ^1.0.3
  #file_picker: ^5.2.10
  firebase_auth: ^5.5.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_chat_types: ^3.6.1
  flutter_chat_ui: ^2.3.1
  flutter_easyloading: ^3.0.5
  flutter_firebase_chat_core: ^1.6.7
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_tags_x: ^1.1.0
  #flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.2.2
  footer: ^0.0.4
  get: ^4.0.0-nullsafety.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_picker: ^1.1.2
  purchases_flutter: ^8.8.1
  intl: ^0.20.2
  intl_phone_field: ^3.1.0
  just_audio: ^0.10.0
  just_audio_background: ^0.0.1-beta.10
  lottie: ^3.3.0
  mailer: ^6.0.1
  mime: ^2.0.0
  miniplayer: ^1.0.1
  modal_bottom_sheet: ^3.0.0-pre
  my_fatoorah: ^3.2.0
  octo_image: ^2.1.0
  open_filex: ^4.7.0
  path_provider: ^2.1.4
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.0+1
  provider: ^6.0.5
  readmore: ^3.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  smooth_star_rating_null_safety: ^1.0.4+2
  sms_autofill: ^2.3.0
  supercharged: ^2.1.1
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.11
  uuid: ^4.2.2
  very_good_analysis: ^8.0.0
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.9.4
  date_format: ^2.0.7
  transparent_image: ^2.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  device_info_plus: ^11.3.3
  flutter_instagram_stories: ^1.0.3+2
  flutter_cache_manager: ^3.3.1
  photo_manager: ^3.0.0
  flutter_screenutil: ^5.9.0
  # video_player: ^2.9.5
  responsive_sizer: ^3.3.0+1
  flutter_carousel_media_slider: ^0.0.2
  youtube_player_iframe: ^4.0.4
  flutter_rating_bar: ^4.0.1
  custom_progress_button: ^2.0.1
  liquid_progress_indicator_v2: ^0.5.0
  flutter_gemini: ^3.0.0
  # dash_chat_2: ^0.0.21
  pay: ^3.2.1
  win32: ^5.5.4
  http: ^1.2.2
  camera: ^0.11.0+2
  path: ^1.9.0
  google_generative_ai: ^0.4.6
  loading_animation_widget: ^1.3.0
  e_book_reader: ^0.0.11
  photo_view: ^0.15.0
  fl_chart: ^1.0.0
  lazy_load_scrollview: ^1.3.0
  flutter_html: ^3.0.0-beta.2
  package_info_plus: ^8.3.0
  timeago: ^3.7.0
  jwt_decoder: ^2.0.1
  firebase_remote_config: ^5.4.3

dependency_overrides:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
    
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

flutter_gen:
  output: lib/gen/
  synthetic-package: false